### ISSUE TITLE
Dialouge won't start until right character selected (Gaelyn and Riar)

### ISSUE THREAD

**Issue by JessicaQC** [ElHobbitto/PapayaGame#1]
Have to click on Gaelyn and Riar to start dialogue, in which they will repeat the first line every time pressed. If either character is pressed after pressing continue, then the first line of dialogue is repeated, and the dialogue will start from the beginning after pressing continue.

**Version**
- 0.1 Alpha

Reproduce for Gaelyn Scene 1:
1. Go to Start Game
2. Click on Gaelyn
3. First line of dialogue will appear

Reproduce for Gaelyn Scene 2:
1. End Minigame
2. Click Gaelyn
3. First line of dialogue for this scene will appear

Reproduce for Riar:
1. Click on map
2. Travel to New Destination
3. Click on Riar
4. First line of dialogue will repeat

For All:
Clicking on Gaelyn or Riar after pressing continue at any point will result in the first line of dialouge being repeated, and the exchange will start from the beginning again.

**Expected behavior**
Dialogue to begin on scene start up/when continue button is pressed. Clicking character should do nothing

**Desktop System (please complete the following information):**
- OS: Windows10

**Comment by ElHobbitto** [comment]
characters no longer repeat dialogue issue fixed by Kyle Mathews
