### ISSUE TITLE
Dialogue Completely Skippable If Recipe or Map activated 

### ISSUE THREAD

**Issue by JessicaQC** [ElHobbitto/PapayaGame#2]
**Describe the bug**
Dialogue can be skipped entirely by pressing the map or recipe book and either playing the recipe or travelling immediately. This occurs for both Gaelyn and Riar
 
**Version**
- 0.1 Alpha
- 
Reproduce for Gaelyn first dialouge scene:
1. Click on Start Game
2. Click on the Recipe Book Icon
3. Press Arrow front page
4. Press arrow under Hellfire and Cheese Toastie
5. Minigame starts (error here)
6. After minigames, new scene, all previous dialouge skipped

Reproduce for Gaelyn second dialogue scene:
1. Follow previous intstructions
2. Complete minigames
3. Click on map icon
4. Move to Arden Northern Boarder (Error here)
5. All dialogue skipped, new scene starts

Reproduce for Riar, Northern Boarder:
1. Follow previous instructions 
2. Click on Recipe Book icon
3. Click arrow under Unicorn Cake (error here)
4. Game Ends 

**Expected behavior**
The recipe and map icons should do nothing/be inactive until the end of dialogue

**Desktop System (please complete the following information):**
- OS: Windows10

**Comment by ElHobbitto** [comment]
can no longer click on map or recipe until after dialogue finishes fixed issue by Kyle Mathews
