### ISSUE TITLE
Can continue playing Slicing minigame after win/loss

### ISSUE THREAD

**Issue by JessicaQC** [ElHobbitto/PapayaGame#3]
**Describe the bug**
In the slicing minigame, after winning or losing and having either the recipe complete or the try again button pop up, the game continues playing and you can fail or win to get the opposite button. This repeats indefinitely, although the buttons will still work.

**Version**
- 0.1 Alpha

**To Reproduce**
1. Go through Gaelyn dialogue
2. Click on the Recipe Book icon
3. Click arrow to under Hellfire and cheese toastie
4. Play through toasting minigame
5. Click on the Green button on the slider during slicer minigame
6. After win condition, click on the red on the slider (error occurs)
7. Reverse steps 5 and 6 to get the reverse loss to win

**Expected behavior**
After failing or winning, minigame stops, and either the try again or recipe complete options depending on win or loss. 

**Screenshots**
![WinLoss_Bug](https://user-images.githubusercontent.com/79950970/117810105-941f1880-b291-11eb-8603-818bdf627457.png)

**Desktop System (please complete the following information):**
- OS: Windows10

**Comment by ElHobbitto** [comment]
fixed issue by Kyle Mathews
